{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "userRhatWorkerIdLabeler.namespaceName" . }}
  labels:
    {{- include "userRhatWorkerIdLabeler.labels" . | nindent 4 }}
{{- end -}}
