{{- if and .Values.deploy .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "userRhatWorkerIdLabeler.serviceAccountName" . }}
  namespace: {{ include "userRhatWorkerIdLabeler.namespaceName" . }}
  labels:
    {{- include "userRhatWorkerIdLabeler.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
